lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    # time of living defined 3600 seconds = 1 hour
    token_ttl: 3600
