lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    # time of living defined 3600 seconds = 1 hour
    token_ttl: 3600
    user_identity_field: username
