controllers:
    resource: ../src/Controller/
    type: attribute
api_login_check:
    path: /api/login
app.redocly:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }
